"""Add store table in app schema

Revision ID: a4f9bd5ebef0
Revises: 5a27ae6ec820
Create Date: 2025-04-14 18:29:37.606326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a4f9bd5ebef0'
down_revision: Union[str, None] = '5a27ae6ec820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_url', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_stores_store_url'), 'stores', ['store_url'], unique=True, schema='app')
    op.create_index('ix_stores_store_url', 'stores', ['store_url'], unique=False, schema='app')
    op.drop_index('ix_stores_store_url', table_name='stores')
    op.drop_table('stores')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('store_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='stores_pkey')
    )
    op.create_index('ix_stores_store_url', 'stores', ['store_url'], unique=False)
    op.drop_index('ix_stores_store_url', table_name='stores', schema='app')
    op.drop_index(op.f('ix_app_stores_store_url'), table_name='stores', schema='app')
    op.drop_table('stores', schema='app')
    # ### end Alembic commands ###
