"""Add shops table

Revision ID: e042a28d3a70
Revises: a4f9bd5ebef0
Create Date: 2025-04-16 19:49:21.978430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e042a28d3a70'
down_revision: Union[str, None] = 'a4f9bd5ebef0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema: Create the 'shops' table in the 'app' schema."""
    # ### commands auto generated by Alembic - START ###
    # Removed create_table('stores', ...) as it was redundant.
    op.create_table('shops',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('shop_domain', sa.String(), nullable=False, comment='The unique *.myshopify.com domain for the shop.'),
        sa.Column('access_token', sa.String(), nullable=False, comment='The offline OAuth access token for the shop.'),
        sa.Column('scopes', sa.String(), nullable=True, comment='Access scopes granted during installation.'),
        sa.Column('installed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the app was installed or token last updated.'),
        sa.Column('uninstalled_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the app was uninstalled (if applicable).'),
        sa.PrimaryKeyConstraint('id'),
        schema='app' # Explicitly specify the schema
    )
    op.create_index(op.f('ix_app_shops_id'), 'shops', ['id'], unique=False, schema='app') # Add schema and potentially adjust F() helper name
    op.create_index(op.f('ix_app_shops_shop_domain'), 'shops', ['shop_domain'], unique=True, schema='app') # Add schema and potentially adjust F() helper name
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema: Drop the 'shops' table from the 'app' schema."""
    # ### commands auto generated by Alembic - START ###
    op.drop_index(op.f('ix_app_shops_shop_domain'), table_name='shops', schema='app') # Add schema
    op.drop_index(op.f('ix_app_shops_id'), table_name='shops', schema='app') # Add schema
    op.drop_table('shops', schema='app') # Add schema
    # Removed drop_table('stores', ...) as it was redundant.
    # ### end Alembic commands ###
