"""Move shops table to app schema

Revision ID: fb1251f1e43a
Revises: ff0a9dfe8c22
Create Date: 2025-04-16 20:07:27.986502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb1251f1e43a'
down_revision: Union[str, None] = 'ff0a9dfe8c22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_domain', sa.String(), nullable=False, comment='The unique *.myshopify.com domain for the shop.'),
    sa.Column('access_token', sa.String(), nullable=False, comment='The offline OAuth access token for the shop.'),
    sa.Column('scopes', sa.String(), nullable=True, comment='Access scopes granted during installation.'),
    sa.Column('installed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the app was installed or token last updated.'),
    sa.Column('uninstalled_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the app was uninstalled (if applicable).'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_shops_id'), 'shops', ['id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_shops_shop_domain'), 'shops', ['shop_domain'], unique=True, schema='app')
    op.drop_index('ix_shops_id', table_name='shops')
    op.drop_index('ix_shops_shop_domain', table_name='shops')
    op.drop_table('shops')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shops',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shop_domain', sa.VARCHAR(), autoincrement=False, nullable=False, comment='The unique *.myshopify.com domain for the shop.'),
    sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=False, comment='The offline OAuth access token for the shop.'),
    sa.Column('scopes', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Access scopes granted during installation.'),
    sa.Column('installed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Timestamp when the app was installed or token last updated.'),
    sa.Column('uninstalled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='Timestamp when the app was uninstalled (if applicable).'),
    sa.PrimaryKeyConstraint('id', name='shops_pkey')
    )
    op.create_index('ix_shops_shop_domain', 'shops', ['shop_domain'], unique=True)
    op.create_index('ix_shops_id', 'shops', ['id'], unique=False)
    op.drop_index(op.f('ix_app_shops_shop_domain'), table_name='shops', schema='app')
    op.drop_index(op.f('ix_app_shops_id'), table_name='shops', schema='app')
    op.drop_table('shops', schema='app')
    # ### end Alembic commands ###
